export const CUSTOMERS_LOADING = 'CUSTOMERS_LOADING';
export const CUSTOMERS_FAILED = 'CUSTOMERS_FAILED';
export const ADD_CUSTOMERS = 'ADD_CUSTOMERS';

export const INVENTORY_LOADING = 'INVENTORY_LOADING';
export const INVENTORY_FAILED = 'INVENTORY_FAILED';
export const ADD_INVENTORY = 'ADD_INVENTORY';

export const ORDERS_LOADING = 'ORDERS_LOADING';
export const ORDERS_FAILED = 'ORDERS_FAILED';
export const ADD_ORDERS = 'ADD_ORDERS';

export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';

export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';
export const ADD_USERS = 'ADD_USERS';
